# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geometricDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from resources import geometric_img_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(829, 491)
        Dialog.setStyleSheet("#Dialog{\n"
"    background-color: rgb(40, 40, 40);\n"
"}\n"
"#widget{\n"
"    background-color: rgb(150, 150, 150);\n"
"    border-radius: 4px;\n"
"}\n"
"#RWL0{\n"
"        background-color: rgb(70,70,70); \n"
"        border-radius: 4px;\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#RWL1{\n"
"        background-color: rgb(70,70,70); \n"
"        border-radius: 4px;\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#RWH0{\n"
"        background-color: rgb(70,70,70); \n"
"        border-radius: 4px;\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#RWH1{\n"
"        background-color: rgb(70,70,70); \n"
"        border-radius: 4px;\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#RWE0{\n"
"        background-color: rgb(70,70,70); \n"
"        border-radius: 4px;\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#label_50{\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#label_51{\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#label_52{\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#label_53{\n"
"        color: rgb(249,249,249);\n"
"}\n"
"#label_54{\n"
"        color: rgb(249,249,249);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_52 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.gridLayout.addWidget(self.label_52, 2, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.RWH1 = QtWidgets.QDoubleSpinBox(Dialog)
        self.RWH1.setAlignment(QtCore.Qt.AlignCenter)
        self.RWH1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.RWH1.setObjectName("RWH1")
        self.gridLayout.addWidget(self.RWH1, 3, 3, 1, 1)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("background-color: rgb(77, 77, 77);\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(780, 320))
        self.label.setMaximumSize(QtCore.QSize(800, 400))
        self.label.setWhatsThis("")
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 5)
        self.RWL1 = QtWidgets.QDoubleSpinBox(Dialog)
        self.RWL1.setAlignment(QtCore.Qt.AlignCenter)
        self.RWL1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.RWL1.setObjectName("RWL1")
        self.gridLayout.addWidget(self.RWL1, 3, 1, 1, 1)
        self.label_54 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout.addWidget(self.label_54, 2, 4, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.label_50 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.gridLayout.addWidget(self.label_50, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.RWH0 = QtWidgets.QDoubleSpinBox(Dialog)
        self.RWH0.setAlignment(QtCore.Qt.AlignCenter)
        self.RWH0.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.RWH0.setObjectName("RWH0")
        self.gridLayout.addWidget(self.RWH0, 3, 2, 1, 1)
        self.RWE0 = QtWidgets.QDoubleSpinBox(Dialog)
        self.RWE0.setAlignment(QtCore.Qt.AlignCenter)
        self.RWE0.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.RWE0.setObjectName("RWE0")
        self.gridLayout.addWidget(self.RWE0, 3, 4, 1, 1)
        self.label_53 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.gridLayout.addWidget(self.label_53, 2, 3, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.RWL0 = QtWidgets.QDoubleSpinBox(Dialog)
        self.RWL0.setFrame(False)
        self.RWL0.setAlignment(QtCore.Qt.AlignCenter)
        self.RWL0.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.RWL0.setObjectName("RWL0")
        self.gridLayout.addWidget(self.RWL0, 3, 0, 1, 1)
        self.label_51 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.gridLayout.addWidget(self.label_51, 2, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_52.setText(_translate("Dialog", "H0"))
        self.RWH1.setSuffix(_translate("Dialog", " cm"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><img src=\":/geometric/DialogPicT2.PNG\"/></p></body></html>"))
        self.RWL1.setSuffix(_translate("Dialog", " cm"))
        self.label_54.setText(_translate("Dialog", "E0"))
        self.label_50.setText(_translate("Dialog", "L0"))
        self.RWH0.setSuffix(_translate("Dialog", " cm"))
        self.RWE0.setSuffix(_translate("Dialog", " cm"))
        self.label_53.setText(_translate("Dialog", "H1"))
        self.RWL0.setSuffix(_translate("Dialog", " cm"))
        self.label_51.setText(_translate("Dialog", "L1"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
